### PR TITLE
Add new endpoint - List Emails

### PR DESCRIPTION
**Pull request by john-joe-givery**
Adds new endpoint to retrieve all emails (public and private) associated with the authenticated user (requires `user:email` scope)

### CODE REVIEW

**Review by BenFradet — DISMISSED** [review]
Thanks :+1:

**Comment by fedefernandez** [comment]
Thanks! Do you mind to add the following in the build.sbt ([here](https://github.com/47degrees/github4s/blob/main/build.sbt#L45)):

```scala
ProblemFilters.exclude[ReversedMissingMethodProblem]("github4s.algebras.Users.getEmails")
```

**Review by fedefernandez — APPROVED** [review]

**Comment by fedefernandez** [comment]
Thanks for your contribution, @john-joe-givery. I'll release a new version soon

**Comment by john-joe-givery** [comment]
Thanks for the approval! What's the status on the new release? I noticed the CI on the master merge failed. Is there something I can do to assist in getting it released?

**Comment by john-joe-givery** [comment]
FYI after this was merged in, the microsite no longer seems to be working. I'm not sure if that's related to this change, but it might be good to look into when you get a chance.

**Pull request merged**
