### PR TITLE
Added issue label api

### PR DESCRIPTION
**Pull request by loonydev**
Hi, 

During using of this library I found missed API's: 
- [createLabel](https://developer.github.com/v3/issues/labels/#create-a-label), 
- [updateLabel](https://developer.github.com/v3/issues/labels/#update-a-label)
- [deleteLabel](https://developer.github.com/v3/issues/labels/#delete-a-label)

This endpoint's need to create a custom label for repository, for example, specify color.

For this reason I must to change domain of Label, this changes a breaking, so maybe it's reasonable to create other model like  `LabelData`.

### CODE REVIEW

**Review by juanpedromoreno — COMMENTED** [review]
Thanks for your time @loonydev . The code is looking great.

It would be nice if you can add some docs too :)

**Comment by loonydev** [comment]
Hi @juanpedromoreno,
Thx, sure will do today.

**Review by juanpedromoreno — APPROVED** [review]
Thanks @loonydev !

**Comment by juanpedromoreno** [comment]
Ooops the [CreateLabel integration test failed](https://github.com/47degrees/github4s/runs/1127689980?check_suite_focus=true#step:10:513) :( , I forgot running the integration tests (manually), as they are not running in forks

**Comment by juanpedromoreno** [comment]
https://github.com/47degrees/github4s/pull/550 should fix the test :)

**Comment by loonydev** [comment]
Oops, sorry, forget to change the status. 
Thanks you for great library.

**Pull request merged**
